# Generated by Django 3.0.5 on 2020-04-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
