# Generated by Django 3.0.6 on 2020-05-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, default='Bangkok', max_length=100, null=True)),
                ('province', models.CharField(blank=True, default='Bangkok', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, default='10260', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='Thailand', max_length=100, null=True)),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.BillingProfile')),
            ],
        ),
    ]
