# Generated by Django 3.0.6 on 2020-05-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
