# Generated by Django 3.0.6 on 2020-05-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], max_length=100, null=True),
        ),
    ]
