# Generated by Django 3.0.6 on 2020-05-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('shipped', 'Shipped'), ('competed', 'Completed'), ('refunded', 'Refunded'), ('processing', 'Processing')], max_length=100, null=True),
        ),
    ]
