# Generated by Django 3.0.6 on 2020-05-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20200527_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='default',
        ),
        migrations.AddField(
            model_name='card',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
