# Generated by Django 3.0.6 on 2020-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=100, null=True),
        ),
    ]
